import fs from 'node:fs';
import path from 'node:path';

export const AUTO_GENERATED_MARKER =
  '// AUTO-GENERATED by auto-entrypoints — do not edit manually.';

/**
 * Converts a valid Sass partial basename into its Shopify-facing entrypoint
 * basename. Only lowercase letters and internal hyphens are permitted, so
 * every generated asset has one unambiguous, readable kebab-case name.
 *
 * @param {string} sourceName - source directory name (e.g. "component")
 * @param {string} partialBaseName - partial filename without leading `_` or extension
 * @returns {string}
 */
export const getEntrypointBaseName = (sourceName, partialBaseName) => {
  if (!/^[a-z]+(?:-[a-z]+)*$/.test(partialBaseName)) {
    throw new Error(
      `[auto-entrypoints] invalid partial name "_${partialBaseName}.scss". ` +
        'Use lowercase letters and hyphens only (for example, "_button-group.scss").'
    );
  }

  const sourcePrefix = `${sourceName}-`;
  const nameWithoutDuplicatePrefix = partialBaseName.startsWith(sourcePrefix)
    ? partialBaseName.slice(sourcePrefix.length)
    : partialBaseName;

  return `${sourceName}-${nameWithoutDuplicatePrefix}`;
};

/**
 * Scans each source directory for `_name.scss` partials and writes (or overwrites)
 * a corresponding entrypoint in `entrypointsDir`.
 *
 * @param {{ dir: string, importBase: string }[]} autoSources
 * @param {string} entrypointsDir - absolute path
 * @param {string} stylesRootLabel - label for the generated file header comment
 * @returns {Set<string>} filenames generated in this run (e.g. "component-card.scss")
 */
export const generateEntrypointsFromSources = (autoSources, entrypointsDir, stylesRootLabel) => {
  const generatedFiles = new Set();
  const sourcesByEntrypoint = new Map();

  for (const { dir, importBase } of autoSources) {
    if (!fs.existsSync(dir)) continue;

    for (const file of fs.readdirSync(dir)) {
      if (!file.startsWith('_') || !file.endsWith('.scss')) continue;

      const baseName = file.slice(1, -5); // strips "_" and ".scss"
      const prefixedBaseName = getEntrypointBaseName(importBase, baseName);
      const entryFileName = `${prefixedBaseName}.scss`;
      const entryPath = path.join(entrypointsDir, entryFileName);
      const importPath = `../styles/${importBase}/${baseName}`;

      const sourcePath = path.join(dir, file);
      const conflictingSource = sourcesByEntrypoint.get(entryFileName);

      if (conflictingSource) {
        throw new Error(
          `[auto-entrypoints] name collision: "${conflictingSource}" and "${sourcePath}" both generate "${entryFileName}". ` +
            'Use hyphens as the canonical separator and rename one of the partials.'
        );
      }

      sourcesByEntrypoint.set(entryFileName, sourcePath);

      if (fs.existsSync(entryPath)) {
        const existingContent = fs.readFileSync(entryPath, 'utf-8');

        if (!existingContent.startsWith(AUTO_GENERATED_MARKER)) {
          throw new Error(
            `[auto-entrypoints] refusing to overwrite manual entrypoint "${entryPath}" generated from "${sourcePath}".`
          );
        }
      }

      const content = `${AUTO_GENERATED_MARKER}\n// Source: ${stylesRootLabel}/${importBase}/_${baseName}.scss\n@use '${importPath}';\n`;

      fs.writeFileSync(entryPath, content);
      generatedFiles.add(entryFileName);
    }
  }

  return generatedFiles;
};

/**
 * Removes auto-generated entrypoints whose source partial no longer exists.
 * Never touches files without the AUTO_GENERATED_MARKER (manual entrypoints like base.scss).
 *
 * @param {string} entrypointsDir - absolute path
 * @param {Set<string>} expectedFiles - filenames that should be kept
 */
export const cleanupOrphanedEntrypoints = (entrypointsDir, expectedFiles) => {
  for (const file of fs.readdirSync(entrypointsDir)) {
    if (!file.endsWith('.scss')) continue;

    const fullPath = path.join(entrypointsDir, file);
    const content = fs.readFileSync(fullPath, 'utf-8');
    const isAutoGenerated = content.startsWith(AUTO_GENERATED_MARKER);

    if (isAutoGenerated && !expectedFiles.has(file)) {
      fs.unlinkSync(fullPath);
      console.log(`[auto-entrypoints] removed orphaned entrypoint: ${file}`);
    }
  }
};
