import fs from 'node:fs';
import path from 'node:path';

export const AUTO_GENERATED_MARKER =
  '// AUTO-GENERATED by auto-entrypoints — do not edit manually.';

/**
 * Branded type for generated entrypoint filenames (e.g. "component-card.scss").
 * Values can only be produced by {@link generateEntrypointsFromSources}, so call
 * sites can tell generated names apart from arbitrary strings.
 */
export type EntrypointName = string & { readonly __entrypointName: unique symbol };

const toEntrypointName = (fileName: string): EntrypointName =>
  // type-coverage:ignore-next-line the brand can only be produced by an assertion.
  fileName as EntrypointName;

/**
 * Converts a valid Sass partial basename into its Shopify-facing entrypoint
 * basename. Only lowercase letters and internal hyphens are permitted, so
 * every generated asset has one unambiguous, readable kebab-case name.
 *
 * @param sourceName - source directory name (e.g. "component")
 * @param partialBaseName - partial filename without leading `_` or extension
 */
export const getEntrypointBaseName = (sourceName: string, partialBaseName: string): string => {
  if (!/^[a-z]+(?:-[a-z]+)*$/.test(partialBaseName)) {
    throw new Error(
      `[auto-entrypoints] invalid partial name "_${partialBaseName}.scss". ` +
        'Use lowercase letters and hyphens only (for example, "_button-group.scss").'
    );
  }

  const sourcePrefix = `${sourceName}-`;
  const nameWithoutDuplicatePrefix = partialBaseName.startsWith(sourcePrefix)
    ? partialBaseName.slice(sourcePrefix.length)
    : partialBaseName;

  return `${sourceName}-${nameWithoutDuplicatePrefix}`;
};

/**
 * Scans each source directory for `_name.scss` partials and writes (or overwrites)
 * a corresponding entrypoint in `entrypointsDir`.
 *
 * @param autoSources - source directories and their import base names
 * @param entrypointsDir - absolute path
 * @param stylesRootLabel - label for the generated file header comment
 * @returns filenames generated in this run (e.g. "component-card.scss")
 */
export const generateEntrypointsFromSources = (
  autoSources: { dir: string; importBase: string }[],
  entrypointsDir: string,
  stylesRootLabel: string
): Set<EntrypointName> => {
  const generatedFiles = new Set<EntrypointName>();
  const sourcesByEntrypoint = new Map<EntrypointName, string>();

  for (const { dir, importBase } of autoSources) {
    if (!fs.existsSync(dir)) continue;

    for (const file of fs.readdirSync(dir)) {
      if (!file.startsWith('_') || !file.endsWith('.scss')) continue;

      const baseName = file.slice(1, -5); // strips "_" and ".scss"
      const prefixedBaseName = getEntrypointBaseName(importBase, baseName);
      const entryFileName = toEntrypointName(`${prefixedBaseName}.scss`);
      const entryPath = path.join(entrypointsDir, entryFileName);
      const importPath = `../styles/${importBase}/${baseName}`;

      const sourcePath = path.join(dir, file);
      const conflictingSource = sourcesByEntrypoint.get(entryFileName);

      if (conflictingSource) {
        throw new Error(
          `[auto-entrypoints] name collision: "${conflictingSource}" and "${sourcePath}" both generate "${entryFileName}". ` +
            'Use hyphens as the canonical separator and rename one of the partials.'
        );
      }

      sourcesByEntrypoint.set(entryFileName, sourcePath);

      const content = `${AUTO_GENERATED_MARKER}\n// Source: ${stylesRootLabel}/${importBase}/_${baseName}.scss\n@use '${importPath}';\n`;

      if (fs.existsSync(entryPath)) {
        const existingContent = fs.readFileSync(entryPath, 'utf-8');

        if (!existingContent.startsWith(AUTO_GENERATED_MARKER)) {
          throw new Error(
            `[auto-entrypoints] refusing to overwrite manual entrypoint "${entryPath}" generated from "${sourcePath}".`
          );
        }

        if (existingContent === content) {
          generatedFiles.add(entryFileName);
          continue;
        }
      }

      fs.writeFileSync(entryPath, content);
      generatedFiles.add(entryFileName);
    }
  }

  return generatedFiles;
};

/**
 * Removes auto-generated entrypoints whose source partial no longer exists.
 * Never touches files without the AUTO_GENERATED_MARKER (manual entrypoints like base.scss).
 *
 * @param entrypointsDir - absolute path
 * @param expectedFiles - filenames that should be kept
 */
export const cleanupOrphanedEntrypoints = (
  entrypointsDir: string,
  expectedFiles: Set<EntrypointName>
): void => {
  for (const file of fs.readdirSync(entrypointsDir)) {
    if (!file.endsWith('.scss')) continue;

    const fullPath = path.join(entrypointsDir, file);
    const content = fs.readFileSync(fullPath, 'utf-8');
    const isAutoGenerated = content.startsWith(AUTO_GENERATED_MARKER);

    if (isAutoGenerated && !expectedFiles.has(toEntrypointName(file))) {
      fs.unlinkSync(fullPath);
      console.warn(`[auto-entrypoints] removed orphaned entrypoint: ${file}`);
    }
  }
};
